In [5]:
import pandas as pd

portfolios_df = pd.read_csv("../data/fishare_portfolios.csv")
portfolios_df

,sector,registration_date,owner_id,1,2,3,4,5,6,7,...,461,462,463,464,465,466,467,468,469,470
0,Households,1995-12-31,47,170,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Households,1995-12-31,85,170,516.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Government institutions,1995-12-31,250,770,982.0,635.0,1296.0,135.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Non-Financial corporations,1995-12-31,952,328,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Households,1995-12-31,1265,962,170.0,185.0,213.0,535.0,1459.0,1296.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197142,Households,2016-12-31,1307758,432,412.0,1147.0,1866.0,213.0,952.0,1432.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197143,Households,2016-12-31,1307801,1359,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197144,Households,2016-12-31,1307809,30,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197145,Households,2016-12-31,1307828,856,472.0,1471.0,213.0,587.0,272.0,697.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197146,Households,2016-12-31,1308349,591,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
signatures_df = pd.read_csv("../data/fishare_signatures.csv")
signatures_df

,sector,registration_date,owner_id,1,2,3,4,5,6,7,...,461,462,463,464,465,466,467,468,469,470
0,Non-Financial corporations,1995-12-31,1162756,0.400000,0.200000,0.100000,0.100000,0.100000,0.100000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Households,1995-12-31,589052,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Households,1995-12-31,87479,0.400000,0.200000,0.200000,0.200000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Households,1995-12-31,900157,0.500000,0.500000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Households,1995-12-31,941383,0.171429,0.171429,0.114286,0.085714,0.085714,0.057143,0.057143,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197142,Households,2016-12-31,20114,0.392252,0.251816,0.118644,0.099274,0.050847,0.024213,0.014528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197143,Households,2016-12-31,522415,0.109290,0.098361,0.098361,0.092896,0.087432,0.060109,0.054645,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197144,Non-Financial corporations,2016-12-31,428955,0.053816,0.052838,0.051859,0.045010,0.044031,0.042074,0.040117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197145,EU institutions,2016-12-31,1019956,0.062417,0.062417,0.061089,0.053121,0.049137,0.046481,0.035857,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197146,Households,2016-12-31,1279977,0.096203,0.058228,0.043038,0.043038,0.040506,0.035443,0.032911,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN