In [1]:
import wrds
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

In [2]:
conn = wrds.Connection(wrds_username="youngjins")

Loading library list...
Done

In [4]:
target_library = "taqsamp_all"
tables_in_lib = conn.list_tables(library=target_library)
print(f"{target_library} 라이브러리 내 테이블: {tables_in_lib}")

taqmsamp_all 라이브러리 내 테이블: ['arca_idf_x100_20211004', 'arca_idf_x100_20211005', 'arca_idf_x101_20211004', 'arca_idf_x101_20211005', 'arca_idf_x102_20211004', 'arca_idf_x102_20211005', 'arca_idf_x103_20211004', 'arca_idf_x103_20211005', 'arca_idf_x104_20211004', 'arca_idf_x104_20211005', 'arca_idf_x105_20211004', 'arca_idf_x105_20211005', 'arca_idf_x110_20211004', 'arca_idf_x110_20211005', 'arca_idf_x111_20211004', 'arca_idf_x111_20211005', 'arca_idf_x112_20211004', 'arca_idf_x112_20211005', 'arca_idf_x113_20211004', 'arca_idf_x113_20211005', 'arca_idf_x114_20211004', 'arca_idf_x114_20211005', 'arca_idf_x34_20211004', 'arca_idf_x34_20211005', 'arca_idf_x3_20211004', 'arca_idf_x3_20211005', 'cqm_20090213', 'ctm_20090213', 'ix_cqm_20090213', 'ix_ctm_20090213', 'ix_nbbom_20090213', 'nbbom_20090213', 'nyse_idf_x100_20211004', 'nyse_idf_x100_20211005', 'nyse_idf_x101_20211004', 'nyse_idf_x101_20211005', 'nyse_idf_x102_20211004', 'nyse_idf_x102_20211005', 'nyse_idf_x103_20211004', 'nyse_idf_x103_20211005', 'nyse_idf_x104_20211004', 'nyse_idf_x104_20211005', 'nyse_idf_x105_20211004', 'nyse_idf_x105_20211005', 'nyse_idf_x110_20211004', 'nyse_idf_x110_20211005', 'nyse_idf_x111_20211004', 'nyse_idf_x111_20211005', 'nyse_idf_x112_20211004', 'nyse_idf_x112_20211005', 'nyse_idf_x113_20211004', 'nyse_idf_x113_20211005', 'nyse_idf_x114_20211004', 'nyse_idf_x114_20211005', 'nyse_idf_x34_20211004', 'nyse_idf_x34_20211005', 'nyse_idf_x3_20211004', 'nyse_idf_x3_20211005']

In [ ]:
# x3 기본 주문장의 스냅샷 데이터 샘플 확인 (처음 10개 행)
target_table = "nyse_idf_x3_20211004"
quote_data = conn.get_table(library=target_library, table=target_table)

In [7]:
quote_data

,msgtype,seqnumber,symbol,marketid,systemid,exchange,securitytype,lot_size,prevcloseprice,prevclosevolume,price_resolution,round_lot,mpv,unit_of_trade,sym_root,sym_suffix
0,3.0,2.0,WTM,1.0,51.0,N,C,100.0,1069.01,0.0,0.0,N,0.0001,1.0,WTM,None
1,3.0,5.0,Y,1.0,51.0,N,C,100.0,631.40,0.0,0.0,N,0.0001,1.0,Y,None
2,3.0,8.0,SPB,1.0,51.0,N,C,100.0,98.06,0.0,0.0,N,0.0001,1.0,SPB,None
3,3.0,11.0,UVE,1.0,51.0,N,C,100.0,12.98,0.0,0.0,N,0.0001,1.0,UVE,None
4,3.0,14.0,POR,1.0,51.0,N,C,100.0,47.29,0.0,0.0,N,0.0001,1.0,POR,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11268,3.0,1188.0,USM,1.0,59.0,N,C,100.0,32.00,0.0,0.0,N,0.0001,1.0,USM,None
11269,3.0,1191.0,VPV,1.0,59.0,N,U,100.0,13.26,0.0,0.0,N,0.0001,1.0,VPV,None
11270,3.0,1194.0,VTR,1.0,59.0,N,C,100.0,56.08,0.0,0.0,N,0.0001,1.0,VTR,None
11271,3.0,1197.0,WIT,1.0,59.0,N,A,100.0,8.94,0.0,0.0,N,0.0001,1.0,WIT,None
11272,3.0,1200.0,WLK,1.0,59.0,N,C,100.0,93.76,0.0,0.0,N,0.0001,1.0,WLK,None

In [8]:
quote_data.columns

Index(['msgtype', 'seqnumber', 'symbol', 'marketid', 'systemid', 'exchange',
       'securitytype', 'lot_size', 'prevcloseprice', 'prevclosevolume',
       'price_resolution', 'round_lot', 'mpv', 'unit_of_trade', 'sym_root',
       'sym_suffix'],
      dtype='object')

In [11]:
# x34 기본 주문장의 스냅샷 데이터 샘플 확인 (처음 10개 행)
target_table = "nyse_idf_x34_20211004"
quote_data = conn.get_table(library=target_library, table=target_table)
quote_data

,msgtype,seqnumber,symbol,sourcetime,symbolseqnum,time,securitystatus,haltcondition,price1,price2,ssr_triggering_exch,ssr_triggering_vol,ssrstate,marketstate
0,34.0,4.0,WTM,1347.494788,1.0,NaN,P,~,NaN,NaN,None,NaN,~,P
1,34.0,7.0,Y,1347.494828,1.0,NaN,P,~,NaN,NaN,None,NaN,~,P
2,34.0,10.0,SPB,1347.494873,1.0,NaN,P,~,NaN,NaN,None,NaN,~,P
3,34.0,13.0,UVE,1347.495380,1.0,NaN,P,~,NaN,NaN,None,NaN,~,P
4,34.0,16.0,POR,1347.495675,1.0,NaN,P,~,NaN,NaN,None,NaN,~,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47039,34.0,30459875.0,CXP,57833.155362,37793.0,NaN,X,~,NaN,NaN,None,NaN,~,X
47040,34.0,30460437.0,VTR,57836.529879,254989.0,NaN,X,~,NaN,NaN,None,NaN,~,X
47041,34.0,30460930.0,DXC,57838.702412,134909.0,NaN,X,~,NaN,NaN,None,NaN,~,X
47042,34.0,30460979.0,ICL,57844.449087,9442.0,NaN,X,~,NaN,NaN,None,NaN,~,X
47043,34.0,30460980.0,ITCB RTWI,60300.002969,6.0,NaN,X,~,NaN,NaN,None,NaN,~,X

In [12]:
quote_data.columns

Index(['msgtype', 'seqnumber', 'symbol', 'sourcetime', 'symbolseqnum', 'time',
       'securitystatus', 'haltcondition', 'price1', 'price2',
       'ssr_triggering_exch', 'ssr_triggering_vol', 'ssrstate', 'marketstate'],
      dtype='object')